name: Continuous Deployment

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:

  deploy-cdk:
    
    name: Deploy CDK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ACCESS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Cache Node Modules
        uses: actions/cache@v4
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Node Modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Create Mohager .env File
        uses: iamsauravsharma/create-dotenv@v2.0.1
        with:
          input-prefix: 'WEBSITE_' # Needed To Prevent GitHub Variables From Propagating To Lambda
          file-path: '.env'
        env:
          WEBSITE_NODE_ENV: "production"

      - name: Build
        run: npm run build-lambda
      
      - name: Bootstrap
        run: npm run bootstrap

      - name: Deploy
        run: npm run deploy